wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1650547865
    t:
      1:
      - 2
      - 3
      - 5
      3:
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: mnist
early_stopping:
  desc: null
  value: 5
fill_func:
  desc: null
  value: ffill
lam_data_multiplier:
  desc: null
  value: 1
lam_low_first:
  desc: null
  value: true
lam_lower_bound:
  desc: null
  value: 0.0
lam_max:
  desc: null
  value: 3
lam_upper_bound:
  desc: null
  value: 0.0
lam_zero:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 0.01
pacing_func:
  desc: null
  value: naive_grad
score_grav:
  desc: null
  value: 0.1
score_lookback:
  desc: null
  value: 3
scoring_func:
  desc: null
  value: grads
