FROM tensorflow/tensorflow:latest-gpu

RUN pip install matplotlib
RUN pip install pandas
RUN pip install numpy
RUN pip install tensorflow_addons
RUN pip install tensorflow_datasets
RUN pip install tensorflow_probability
RUN pip install pyyaml h5py




